import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Mail, X, ExternalLink } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { PageHeader } from '@/components/layout/PageHeader';
import { Table, TBody, TD, TH, THead, TR } from '@/components/ui/table';
import { api } from '@/lib/api';
import { useAuthStore } from '@/stores/auth';
import { relativeTime } from '@/lib/utils';

interface Lead {
  id: string;
  fullName: string | null;
  email: string;
  company: string | null;
}

interface EmailMessage {
  id: string;
  toEmail: string;
  subject: string;
  bodyHtml: string;
  bodyText: string | null;
  status: string;
  sentAt: string | null;
  createdAt: string;
  lead: Lead | null;
}

const STATUS_COLORS: Record<string, string> = {
  SENT: 'green',
  QUEUED: 'yellow',
  SENDING: 'blue',
  FAILED: 'red',
  BOUNCED: 'red',
  OPENED: 'purple',
  CLICKED: 'purple',
};

export function SentEmailsPage() {
  const { workspace } = useAuthStore();
  const wsId = workspace?.id;
  const [preview, setPreview] = useState<EmailMessage | null>(null);
  const [statusFilter, setStatusFilter] = useState('');

  const emailsQ = useQuery({
    queryKey: ['emails', wsId, statusFilter],
    queryFn: () =>
      api.get<EmailMessage[]>(
        `/workspaces/${wsId}/emails${statusFilter ? `?status=${statusFilter}` : ''}`,
      ),
    enabled: !!wsId,
  });

  const emails = emailsQ.data ?? [];

  return (
    <>
      <PageHeader
        title="Sent Emails"
        description="Emails generated by AI and sent to your leads."
        actions={
          <select
            className="h-9 rounded-md border border-input bg-transparent px-3 text-sm"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="">All statuses</option>
            <option value="SENT">Sent</option>
            <option value="QUEUED">Queued</option>
            <option value="FAILED">Failed</option>
            <option value="OPENED">Opened</option>
            <option value="CLICKED">Clicked</option>
            <option value="BOUNCED">Bounced</option>
          </select>
        }
      />

      <div className="space-y-4 p-8">
        {/* Stats bar */}
        <div className="grid grid-cols-3 gap-4 sm:grid-cols-6">
          {['SENT', 'QUEUED', 'FAILED', 'OPENED', 'CLICKED', 'BOUNCED'].map((s) => {
            const count = emails.filter((e) => e.status === s).length;
            return (
              <Card
                key={s}
                className="cursor-pointer transition-shadow hover:shadow-md"
                onClick={() => setStatusFilter(statusFilter === s ? '' : s)}
              >
                <CardContent className="p-4">
                  <div className="text-2xl font-bold">{count}</div>
                  <div className="text-xs text-muted-foreground">{s}</div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        <Card>
          <CardContent className="p-0">
            <Table>
              <THead>
                <TR>
                  <TH>To</TH>
                  <TH>Subject</TH>
                  <TH>Lead</TH>
                  <TH>Status</TH>
                  <TH>Sent</TH>
                  <TH>Preview</TH>
                </TR>
              </THead>
              <TBody>
                {emails.map((e) => (
                  <TR key={e.id}>
                    <TD className="font-medium">{e.toEmail}</TD>
                    <TD className="max-w-xs truncate">{e.subject}</TD>
                    <TD>
                      {e.lead ? (
                        <span className="text-sm">
                          {e.lead.fullName ?? e.lead.email}
                          {e.lead.company && (
                            <span className="ml-1 text-muted-foreground">· {e.lead.company}</span>
                          )}
                        </span>
                      ) : (
                        '—'
                      )}
                    </TD>
                    <TD>
                      <Badge
                        variant="muted"
                        className={
                          STATUS_COLORS[e.status] === 'green'
                            ? 'bg-emerald-100 text-emerald-700'
                            : STATUS_COLORS[e.status] === 'red'
                              ? 'bg-red-100 text-red-700'
                              : STATUS_COLORS[e.status] === 'purple'
                                ? 'bg-purple-100 text-purple-700'
                                : STATUS_COLORS[e.status] === 'yellow'
                                  ? 'bg-yellow-100 text-yellow-700'
                                  : 'bg-blue-100 text-blue-700'
                        }
                      >
                        {e.status}
                      </Badge>
                    </TD>
                    <TD className="text-muted-foreground">
                      {e.sentAt ? relativeTime(e.sentAt) : relativeTime(e.createdAt)}
                    </TD>
                    <TD>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => setPreview(e)}
                        className="gap-1"
                      >
                        <ExternalLink size={13} /> View
                      </Button>
                    </TD>
                  </TR>
                ))}
                {emails.length === 0 && !emailsQ.isLoading && (
                  <TR>
                    <TD colSpan={6} className="p-10 text-center text-sm text-muted-foreground">
                      <Mail className="mx-auto mb-3 opacity-30" size={32} />
                      No emails yet. Run a workflow or campaign to start sending.
                    </TD>
                  </TR>
                )}
                {emailsQ.isLoading && (
                  <TR>
                    <TD colSpan={6} className="p-8 text-center text-sm text-muted-foreground">
                      Loading…
                    </TD>
                  </TR>
                )}
              </TBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      {/* Preview Modal */}
      {preview && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
          onClick={() => setPreview(null)}
        >
          <div
            className="relative max-h-[80vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-card shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header */}
            <div className="sticky top-0 flex items-start justify-between border-b border-border bg-card p-5">
              <div>
                <div className="font-semibold">{preview.subject}</div>
                <div className="mt-0.5 text-xs text-muted-foreground">
                  To: {preview.toEmail}
                  {preview.lead?.company && ` · ${preview.lead.company}`}
                </div>
              </div>
              <button
                onClick={() => setPreview(null)}
                className="ml-4 rounded-md p-1 hover:bg-muted"
              >
                <X size={18} />
              </button>
            </div>

            {/* Email body rendered as HTML */}
            <div className="p-6">
              <div
                className="prose prose-sm max-w-none text-foreground"
                dangerouslySetInnerHTML={{ __html: preview.bodyHtml }}
              />
              {preview.bodyText && (
                <details className="mt-6">
                  <summary className="cursor-pointer text-xs text-muted-foreground hover:text-foreground">
                    Plain text version
                  </summary>
                  <pre className="mt-2 whitespace-pre-wrap rounded-md bg-muted p-3 font-mono text-xs">
                    {preview.bodyText}
                  </pre>
                </details>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
